name: Build & Push Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # GHCR permissions
    permissions:
      contents: read
      packages: write

    steps:
      # ------------------------------
      # Checkout repository
      # ------------------------------
      - name: Checkout code
        uses: actions/checkout@v4


      # ------------------------------
      # Setup Docker Buildx
      # ------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ------------------------------
      # Log in to GHCR
      # ------------------------------
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # ------------------------------
      # Build & Push Django WEB image
      # ------------------------------
      - name: Build & push Web API image
        uses: docker/build-push-action@v6
        with:
          context: ./src/web
          file: ./src/web/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/web:latest


      # ------------------------------
      # Build & Push CELERY image
      # ------------------------------
      - name: Build & push Celery Worker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/web
          file: ./src/web/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            CELERY_BUILD=1
          tags: |
            ghcr.io/${{ github.repository }}/celery:latest
